[mypy]
exclude = (?x)(\.venv/)
ignore_missing_imports = True
no_implicit_optional = False

[mypy-tests.*]
disallow_untyped_defs = False

[mypy-database.queries]
disable_error_code = arg-type, union-attr, index, call-overload, assignment

[mypy-database.dashboard_queries]
disable_error_code = arg-type

[mypy-bot.handlers.*]
disable_error_code = union-attr, arg-type, index

[mypy-bot.middlewares.*]
disable_error_code = assignment

[mypy-scraper.wb_client]
disable_error_code = union-attr

[mypy-main]
disable_error_code = union-attr, arg-type
