[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = False
warn_unused_configs = True

[mypy-main]
ignore_errors = True

[mypy-bot.handlers.*]
ignore_errors = True

[mypy-bot.middlewares.*]
ignore_errors = True

[mypy-database.queries]
ignore_errors = True

[mypy-payment.*]
ignore_errors = True

[mypy-scraper.*]
ignore_errors = True

